plugins {
    id 'com.android.application'
}

android {
    namespace 'com.artha.personalfinance'
    compileSdk 35

    defaultConfig {
        applicationId 'com.artha.personalfinance'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
}
