package com.artha.personalfinance;

import android.app.Activity;
import android.content.ActivityNotFoundException;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.util.Base64;
import android.webkit.JavascriptInterface;
import android.webkit.ValueCallback;
import android.webkit.WebChromeClient;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.Toast;

import java.io.OutputStream;
import java.nio.charset.StandardCharsets;

public class MainActivity extends Activity {

    private static final int CREATE_FILE_REQUEST = 1001;
    private static final int OPEN_FILE_REQUEST = 1002;

    private WebView webView;

    // Data waiting to be saved through Android's file picker.
    private String pendingFileName;
    private String pendingMimeType;
    private byte[] pendingFileBytes;

    // Used by <input type="file"> in the web app.
    private ValueCallback<Uri[]> filePathCallback;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        webView = new WebView(this);
        setContentView(webView);

        WebSettings settings = webView.getSettings();

        settings.setJavaScriptEnabled(true);
        settings.setDomStorageEnabled(true);

        // Artha is a trusted local asset.
        settings.setAllowFileAccess(true);

        // JavaScript bridge used only by our bundled Artha HTML.
        webView.addJavascriptInterface(
                new ArthaAndroidBridge(),
                "ArthaAndroid"
        );

        webView.setWebViewClient(new WebViewClient());

        webView.setWebChromeClient(new WebChromeClient() {

            @Override
            public boolean onShowFileChooser(
                    WebView webView,
                    ValueCallback<Uri[]> filePathCallback,
                    FileChooserParams fileChooserParams
            ) {
                // Cancel any previous callback.
                if (MainActivity.this.filePathCallback != null) {
                    MainActivity.this.filePathCallback.onReceiveValue(null);
                }

                MainActivity.this.filePathCallback = filePathCallback;

                try {
                    Intent intent = fileChooserParams.createIntent();

                    startActivityForResult(
                            intent,
                            OPEN_FILE_REQUEST
                    );

                } catch (ActivityNotFoundException e) {
                    MainActivity.this.filePathCallback = null;

                    Toast.makeText(
                            MainActivity.this,
                            "No file picker found",
                            Toast.LENGTH_LONG
                    ).show();

                    return false;
                }

                return true;
            }
        });

        /*
         * This catches normal WebView downloads.
         *
         * The JavaScript bridge below handles blob/data downloads
         * generated by Artha's Export Transactions function.
         */
        webView.setDownloadListener(
                (url, userAgent, contentDisposition, mimeType, contentLength) -> {

                    // If the page gives us a normal URL, let Android's
                    // browser/download system handle it.
                    if (url != null &&
                            (url.startsWith("http://") ||
                             url.startsWith("https://"))) {

                        Intent intent = new Intent(
                                Intent.ACTION_VIEW,
                                Uri.parse(url)
                        );

                        try {
                            startActivity(intent);
                        } catch (ActivityNotFoundException e) {
                            Toast.makeText(
                                    MainActivity.this,
                                    "No app can handle this download",
                                    Toast.LENGTH_LONG
                            ).show();
                        }

                        return;
                    }

                    // Blob/data downloads are handled by ArthaAndroid.
                    if (url != null &&
                            (url.startsWith("blob:") ||
                             url.startsWith("data:"))) {

                        webView.evaluateJavascript(
                                buildBlobReaderJavascript(url),
                                null
                        );
                    }
                }
        );

        // Load the bundled Artha application.
        webView.loadUrl(
                "file:///android_asset/index.html"
        );
    }

    /**
     * JavaScript bridge.
     *
     * The HTML calls:
     *
     * ArthaAndroid.saveFile(filename, mimeType, base64Data)
     *
     * The Android side then opens the Android Save dialog.
     */
    private class ArthaAndroidBridge {

        @JavascriptInterface
        public void saveFile(
                String fileName,
                String mimeType,
                String base64Data
        ) {
            runOnUiThread(() -> {

                try {
                    byte[] bytes = Base64.decode(
                            base64Data,
                            Base64.DEFAULT
                    );

                    pendingFileName = sanitizeFileName(fileName);
                    pendingMimeType =
                            (mimeType == null || mimeType.isEmpty())
                                    ? "application/octet-stream"
                                    : mimeType;

                    pendingFileBytes = bytes;

                    Intent intent = new Intent(
                            Intent.ACTION_CREATE_DOCUMENT
                    );

                    intent.addCategory(
                            Intent.CATEGORY_OPENABLE
                    );

                    intent.setType(pendingMimeType);

                    intent.putExtra(
                            Intent.EXTRA_TITLE,
                            pendingFileName
                    );

                    startActivityForResult(
                            intent,
                            CREATE_FILE_REQUEST
                    );

                } catch (Exception e) {

                    Toast.makeText(
                            MainActivity.this,
                            "Could not prepare export file",
                            Toast.LENGTH_LONG
                    ).show();
                }
            });
        }
    }

    /**
     * JavaScript that converts a blob/data URL into Base64
     * and sends it to Android.
     */
    private String buildBlobReaderJavascript(String url) {

        String safeUrl = url
                .replace("\\", "\\\\")
                .replace("'", "\\'");

        return
                "(function() {" +
                "  var url = '" + safeUrl + "';" +
                "  fetch(url)" +
                "    .then(function(response) { return response.blob(); })" +
                "    .then(function(blob) {" +
                "      var reader = new FileReader();" +
                "      reader.onloadend = function() {" +
                "        var result = reader.result;" +
                "        var comma = result.indexOf(',');" +
                "        var base64 = result.substring(comma + 1);" +
                "        ArthaAndroid.saveFile(" +
                "          'Artha_Transactions.csv'," +
                "          blob.type || 'text/csv'," +
                "          base64" +
                "        );" +
                "      };" +
                "      reader.readAsDataURL(blob);" +
                "    })" +
                "    .catch(function(error) {" +
                "      console.error('Artha download error:', error);" +
                "    });" +
                "})();";
    }

    /**
     * Makes sure a strange filename cannot create a path.
     */
    private String sanitizeFileName(String fileName) {

        if (fileName == null || fileName.trim().isEmpty()) {
            return "Artha_Transactions.csv";
        }

        String cleaned = fileName
                .replace("/", "_")
                .replace("\\", "_")
                .replace(":", "_")
                .replace("*", "_")
                .replace("?", "_")
                .replace("\"", "_")
                .replace("<", "_")
                .replace(">", "_")
                .replace("|", "_");

        if (!cleaned.toLowerCase().endsWith(".csv")) {
            cleaned += ".csv";
        }

        return cleaned;
    }

    @Override
    protected void onActivityResult(
            int requestCode,
            int resultCode,
            Intent data
    ) {
        super.onActivityResult(
                requestCode,
                resultCode,
                data
        );

        // -----------------------------
        // EXPORT
        // -----------------------------
        if (requestCode == CREATE_FILE_REQUEST) {

            if (resultCode == RESULT_OK &&
                    data != null &&
                    data.getData() != null &&
                    pendingFileBytes != null) {

                Uri uri = data.getData();

                try {
                    OutputStream outputStream =
                            getContentResolver().openOutputStream(uri);

                    if (outputStream == null) {
                        throw new Exception(
                                "Could not open output stream"
                        );
                    }

                    outputStream.write(
                            pendingFileBytes
                    );

                    outputStream.flush();
                    outputStream.close();

                    Toast.makeText(
                            this,
                            "Transactions exported successfully",
                            Toast.LENGTH_LONG
                    ).show();

                } catch (Exception e) {

                    Toast.makeText(
                            this,
                            "Export failed: " + e.getMessage(),
                            Toast.LENGTH_LONG
                    ).show();
                }
            }

            // Clear pending export data.
            pendingFileName = null;
            pendingMimeType = null;
            pendingFileBytes = null;

            return;
        }

        // -----------------------------
        // IMPORT
        // -----------------------------
        if (requestCode == OPEN_FILE_REQUEST) {

            if (filePathCallback == null) {
                return;
            }

            Uri[] results = null;

            if (resultCode == RESULT_OK &&
                    data != null &&
                    data.getData() != null) {

                results = new Uri[]{
                        data.getData()
                };
            }

            filePathCallback.onReceiveValue(results);
            filePathCallback = null;
        }
    }

    @Override
    public void onBackPressed() {

        if (webView != null &&
                webView.canGoBack()) {

            webView.goBack();

        } else {

            super.onBackPressed();
        }
    }
}
